config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users
  resources :companies
  resources :funding_rounds
  resources :investors
  resources :jobs

  scope 'analysis', as: :analysis  do
    get 'scatter_plot', to: 'analysis#scatter_plot'
    get 'line_chart_time_alive', to: 'analysis#line_chart_time_alive'
    get 'line_chart_since_2005', to: 'analysis#line_chart_since_2005'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end

  root 'companies#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  belongs_to :company

  def angellist_url
    "https://angel.co/#{company.permaname}/jobs/#{angellist_job_id}" if angellist_job_id
  end

  def compensation_summary
    summary =  ""
    if salary_min && salary_max
      summary += "$ #{number_in_k(salary_min)} - #{number_in_k(salary_max)}"
    end
    if equity_min && equity_max
      summary += "  ·  " unless summary.blank?
      summary += "#{equity_min} - #{equity_max} %"
    end
    summary
  end

  def tags= value
    if value.is_a? Array
      write_attribute(:tags, value)
    elsif value.is_a? String
      write_attribute(:tags, value.split(',').map(&:strip))
    end
  end

private

  def number_in_k number
    number_to_human(number, units: {thousand: 'K'})
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :require_admin,  except: [:index, :show]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.order(:title)
                .includes(:company)
                .paginate(page: params[:page])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :angellist_job_id, :job_type, :location, :role, :salary_min, :salary_max, :currency_code, :equity_min, :equity_max, :equity_cliff, :equity_vest, :remote_ok, :tags, :company_id, :description)
    end
end

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  - %i{ company_id title job_type location role currency_code }.each do |attribute|
    .field
      = f.label attribute
      = f.text_field attribute
  .field
    = f.label :remote_ok
    = f.check_box :remote_ok
  .field
    = f.label :angellist_job_id
    = f.number_field :angellist_job_id, min: 0, step: 1
  .field
    = f.label :description
    = f.text_area :description
  %h4 Salary
  - %i{ salary_min salary_max }.each do |attribute|
    .field
      = f.label attribute
      = f.number_field attribute, step: 1000, min: 0
  %h4 Equity
  - %i{ equity_min equity_max equity_cliff equity_vest }.each do |attribute|
    .field
      = f.label attribute
      = f.number_field attribute, step: 0.01, min: 0
  %h4 Tags
  .field
    = f.label :tags
    = f.text_area :tags, value: f.object.tags.join(', ')



  .actions
    = f.submit 'Save', class: 'btn btn-primary'
    - if not @job.new_record?
      = link_to 'Show', @job
    = link_to 'Back', jobs_path

app/views/jobs/_table.html.haml
- if jobs.any?
  %table.table.table-condensed.table-hover
    %thead
      %tr
        %th Company
        %th Title
        %th Location
        %th Salary & Equity
        - if current_user.try(:admin?)
          %th{colspan: 4} Actions
        - else
          %th{colspan: 2} Actions

    %tbody
      - jobs.each do |job|
        %tr{id: get_html_id(job), title: job.description}
          %td= job.company.try(:name)
          %td= job.title
          %td= job.location
          %td= job.compensation_summary
          %td= link_to 'Angellist', job.angellist_url, target: '_blank' if job.angellist_job_id
          %td= link_to 'Show', job
          - if current_user.try(:admin?)
            %td= link_to 'Edit', edit_job_path(job)
            %td= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }

app/views/jobs/edit.html.haml
%h1 Editing Job
= render 'form'

app/views/jobs/index.html.haml
%h1= "#{@jobs.count} Jobs"

- if current_user.try(:admin?)
  = link_to 'New Job', new_job_path, class: 'btn btn-primary'
  %br

= will_paginate @jobs
= render partial: 'table', locals: { jobs: @jobs }
= will_paginate @jobs

app/views/jobs/new.html.haml
%h1 New Job
= render 'form'

app/views/jobs/show.html.haml
%p
  %b Company:
  = @job.company.name
- %w{title angellist_job_id job_type location remote_ok role currency_code description tags}.each do |attribute|
  %p
    %b= "#{attribute.humanize}:"
    = @job.send(attribute)
- %w{salary_min salary_max}.each do |attribute|
  %p
    %b= "#{attribute.humanize}:"
    = number_to_currency @job.send(attribute), precision: 0 if @job.send(attribute)
- %w{equity_min equity_max equity_cliff equity_vest}.each do |attribute|
  %p
    %b= "#{attribute.humanize}:"
    = @job.send(attribute)

%br
- if current_user.try(:admin?)
  = link_to 'Edit', edit_job_path(@job), class: 'btn btn-default'
= link_to 'Back', jobs_path, class: 'btn btn-default'