config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users
  resources :companies
  resources :funding_rounds
  resources :investors
  resources :jobs

  scope 'analysis', as: :analysis  do
    get 'scatter_plot', to: 'analysis#scatter_plot'
    get 'line_chart_time_alive', to: 'analysis#line_chart_time_alive'
    get 'line_chart_since_2005', to: 'analysis#line_chart_since_2005'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end

  root 'companies#index'
end

app/models/funding_round.rb
class FundingRound < ActiveRecord::Base
  belongs_to :company
  has_and_belongs_to_many :investors, -> { order(:name) }

  scope :order_by_most_recent, -> { order(announced_on: :desc) }
end

app/controllers/funding_rounds_controller.rb
class FundingRoundsController < ApplicationController
  before_action :set_funding_round, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :require_admin,  except: [:index, :show]


  # GET /funding_rounds
  # GET /funding_rounds.json
  def index
    @funding_rounds = FundingRound.order(announced_on: :desc)
                                  .paginate(page: params[:page])
  end

  # GET /funding_rounds/1
  # GET /funding_rounds/1.json
  def show
  end

  # GET /funding_rounds/new
  def new
    @funding_round = FundingRound.new
  end

  # GET /funding_rounds/1/edit
  def edit
  end

  # POST /funding_rounds
  # POST /funding_rounds.json
  def create
    @funding_round = FundingRound.new(funding_round_params)

    respond_to do |format|
      if @funding_round.save
        format.html { redirect_to @funding_round, notice: 'Funding Round was successfully created.' }
        format.json { render :show, status: :created, location: @funding_round }
      else
        format.html { render :new }
        format.json { render json: @funding_round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funding_rounds/1
  # PATCH/PUT /funding_rounds/1.json
  def update
    respond_to do |format|
      if @funding_round.update(funding_round_params)
        format.html { redirect_to @funding_round, notice: 'Funding Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @funding_round }
      else
        format.html { render :edit }
        format.json { render json: @funding_round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funding_rounds/1
  # DELETE /funding_rounds/1.json
  def destroy
    @funding_round.destroy
    respond_to do |format|
      format.html { redirect_to funding_rounds_url, notice: 'Funding Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funding_round
      @funding_round = FundingRound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funding_round_params
      params.require(:funding_round).permit(:company_id, :funding_type, :money_raised_usd, :announced_on, :series)
    end
end

app/views/funding_rounds/_form.html.haml
= form_for @funding_round do |f|
  - if @funding_round.errors.any?
    #error_explanation
      %h2= "#{pluralize(@funding_round.errors.count, "error")} prohibited this funding_round from being saved:"
      %ul
        - @funding_round.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :company_id
    = f.text_field :company_id
  .field
    = f.label :funding_type
    = f.text_field :funding_type
  .field
    = f.label :money_raised_usd
    = f.number_field :money_raised_usd
  .field
    = f.label :announced_on
    = f.date_select :announced_on
  .field
    = f.label :series
    = f.text_field :series
  .actions
    = f.submit 'Save', class: 'btn btn-primary'
    - if not @funding_round.new_record?
      = link_to 'Show', @funding_round
    = link_to 'Back', funding_rounds_path

app/views/funding_rounds/_table.html.haml
%table.table.table-hover.table-condensed
  %thead
    %tr
      %th Company Name
      %th Announced On
      %th Money Raised (USD)
      %th Funding Type
      %th Series
      %th Investors
      - if current_user.try(:admin?)
        %th{colspan: 3} Actions
      - else
        %th{colspan: 1} Actions

  %tbody
    - funding_rounds.each do |funding_round|
      %tr{id: get_html_id(funding_round)}
        %td= funding_round.company.name
        %td= number_to_currency(funding_round.money_raised_usd, precision: 0) if funding_round.money_raised_usd
        %td= funding_round.announced_on.to_s(:simple_date) if funding_round.announced_on
        %td= funding_round.funding_type
        %td= funding_round.series
        %td= funding_round.investors.map(&:name).join(', ').truncate(40) if funding_round.investors.any?
        %td= link_to 'Show', funding_round
        - if current_user.try(:admin?)
          %td= link_to 'Edit', edit_funding_round_path(funding_round)
          %td= link_to 'Destroy', funding_round, method: :delete, data: { confirm: 'Are you sure?' }

app/views/funding_rounds/edit.html.haml
%h1 Editing Funding Round
= render 'form'

app/views/funding_rounds/index.html.haml
%h1= "#{@funding_rounds.count} Funding Rounds"

- if current_user.try(:admin?)
  = link_to 'New Funding Round', new_funding_round_path, class: 'btn btn-primary'
  %br

= will_paginate @funding_rounds
= render partial: 'table', locals: { funding_rounds: @funding_rounds }
= will_paginate @funding_rounds

app/views/funding_rounds/new.html.haml
%h1 New Funding Round
= render 'form'

app/views/funding_rounds/show.html.haml
%p
  %b Company:
  = @funding_round.company.name
%p
  %b Funding type:
  = @funding_round.funding_type
%p
  %b Money raised usd:
  = @funding_round.money_raised_usd
%p
  %b Announced on:
  = @funding_round.announced_on
%p
  %b Series:
  = @funding_round.series

%br
%h3 Investors
= render partial: 'investors/table', locals: { investors: @funding_round.investors }

%br
- if current_user.try(:admin?)
  = link_to 'Edit', edit_funding_round_path(@funding_round), class: 'btn btn-default'
= link_to 'Back', funding_rounds_path, class: 'btn btn-default'