config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users
  resources :companies
  resources :funding_rounds
  resources :investors
  resources :jobs

  scope 'analysis', as: :analysis  do
    get 'scatter_plot', to: 'analysis#scatter_plot'
    get 'line_chart_time_alive', to: 'analysis#line_chart_time_alive'
    get 'line_chart_since_2005', to: 'analysis#line_chart_since_2005'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end

  root 'companies#index'
end

app/views/layouts/_flash.html.haml
- if flash.any?
  .flashes
    - flash.each do |name, msg|
      .flash{class: name}= msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Job Hunt
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js'
    = csrf_meta_tags
  %body

    %a{href: 'https://github.com/enstartup/startups-hunt', target: '_blank'}
      %img{style: 'position: absolute; top: 0; left: 0; border: 0;', src: 'https://camo.githubusercontent.com/8b6b8ccc6da3aa5722903da7b58eb5ab1081adee/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f6f72616e67655f6666373630302e706e67', alt: 'Fork me on GitHub', 'data-canonical-src' => 'https://s3.amazonaws.com/github/ribbons/forkme_left_orange_ff7600.png'}

    .container#header
      .row
        .col-sm-12
          #logo.pull-left
            %h1= link_to 'Job Hunt', root_path
          %ul.nav.nav-pills.pull-right
            %li= link_to 'Scatter Plot', analysis_scatter_plot_path
            %li= link_to 'Line Chart (Time Alive)', analysis_line_chart_time_alive_path
            %li= link_to 'Line Chart (Since 2005)', analysis_line_chart_since_2005_path
            %li= link_to 'Companies', companies_path
            %li= link_to 'Funding Rounds', funding_rounds_path
            %li= link_to 'Investors', investors_path
            %li= link_to 'Jobs', jobs_path
            - if current_user.try(:admin?)
              %li= link_to 'Sidekiq', sidekiq_path
          .clearfix

    .container
      .row
        .col-sm-12
          - if content_for?(:content)
            = yield(:content)
          - else
            = render 'layouts/flash'
            = yield

    .container#footer
      .row
        .col-sm-12
          .pull-left
            - if current_user
              = link_to 'Sign out', destroy_user_session_path, method: :delete
            - else
              = link_to 'Sign in', new_user_session_path

            &nbsp;
            &nbsp;
            &nbsp;

            Data from
            = link_to 'CrunchBase', 'https://www.crunchbase.com/', target: '_blank'
            and
            = succeed '.' do
              = link_to 'AngelList', 'https://angel.co', target: '_blank'
          .pull-right
            Website by
            = succeed '.' do
              = link_to 'Enstartup', 'http://enstartup.com/', target: '_blank'

app/views/layouts/devise.html.haml
- content_for :content do
  .col-sm-6.col-sm-offset-3.col-xs-12#devise
    = render 'layouts/flash'
    = yield
= render template: 'layouts/application'